services:
  - type: web
    name: havengo-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        value: havengo_ug_5^Kp#9mX$2vR!qLz@8wN&bYdEfGhIj
      - key: ENCRYPTION_KEY
        value: havengo-aes-key-32bytes-2026-secure!
      - key: ADMIN_EMAIL
        value: thermypetson@gmail.com
      - key: ADMIN_PHONE
        value: "0757532066"
      - key: ADMIN_PASSWORD
        value: "23.Forlife"
      - key: MAIL_HOST
        value: "smtp.gmail.com"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_SECURE
        value: "false"
      - key: MAIL_USER
        value: "thermypetson@gmail.com"
      - key: MAIL_PASS
        value: "<YOUR_GMAIL_APP_PASSWORD>"
      - key: MAIL_FROM
        value: "HavenGo <thermypetson@gmail.com>"
      - key: FRONTEND_URL
        value: "https://havengo.netlify.app"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_j1DzgMkZf5UW@ep-rough-waterfall-altogw50.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require

